site_name: DIOL Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: orange
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: amber
      accent: deep orange

nav:
  - Home: index.md
  - How to wiki: how-to-wiki.md
  - Server: 
    - server-guide/index.md
    - Slurm: server-guide/slurm.md
    - CTransformer Library: server-guide/ctransformers-library.md
    - Ollama: server-guide/start-kill-ollama.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DIOL-UniTN

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/DIOL-UniTN"  target="_blank" rel="noopener">DIOL UniTN</a>